{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xingyun",
    "module": "multiLang",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "multiLang-1.0.0.aar",
          "url": "multiLang-1.0.0.aar",
          "size": 62828,
          "sha512": "47f44a53d5adddc634b4b9d25a2112ee2b17e6e16aa9edbd3b910bfb53a3c62a2024a2f38399dce8710217562c829f5b35e2eafebc2f62b9198021c314d3bbbe",
          "sha256": "e474e007bd9a702322adb2c36b8ee2e25e9c4ecac99e0cb7ca87f7c2584a48a2",
          "sha1": "136435624d17bfa7b67d770c117a54b00515554d",
          "md5": "6ec90250a31dedfd732b08c7b66665b0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "multiLang-1.0.0.aar",
          "url": "multiLang-1.0.0.aar",
          "size": 62828,
          "sha512": "47f44a53d5adddc634b4b9d25a2112ee2b17e6e16aa9edbd3b910bfb53a3c62a2024a2f38399dce8710217562c829f5b35e2eafebc2f62b9198021c314d3bbbe",
          "sha256": "e474e007bd9a702322adb2c36b8ee2e25e9c4ecac99e0cb7ca87f7c2584a48a2",
          "sha1": "136435624d17bfa7b67d770c117a54b00515554d",
          "md5": "6ec90250a31dedfd732b08c7b66665b0"
        }
      ]
    }
  ]
}
